server:
  port: 8002

spring:

  config:
    import: "${SPRING_CONFIG_IMPORT:optional:configserver:http://localhost:8071}"

  profiles:
    active: "qa"

  application:
    name: "loans"

  datasource:
    url: jdbc:mysql://localhost:3307/loansdb
    username: root
    password: root

  jpa:
    show-sql: true
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: "*"